# Generated by Django 5.1.6 on 2025-03-05 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('process_status', models.CharField(choices=[('1', 'aguardando processamento'), ('2', 'em fila para processamento'), ('3', 'processando'), ('4', 'processado com sucesso'), ('5', 'erro ao processar'), ('6', 'processamento finalizado')], default='1', max_length=30, verbose_name='Status do Processamento')),
                ('start_processing', models.DateTimeField(blank=True, null=True, verbose_name='Incio do Processamento')),
                ('ending_processing', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Processamento')),
                ('mail_sent', models.BooleanField(default=False, verbose_name='Email do lote enviado')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
            ],
            options={
                'verbose_name': 'Planilha',
                'verbose_name_plural': 'Planilhas',
            },
        ),
        migrations.CreateModel(
            name='WorksheetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('process_status', models.CharField(choices=[('1', 'aguardando processamento'), ('2', 'em fila para processamento'), ('3', 'processando'), ('4', 'processado com sucesso'), ('5', 'erro ao processar'), ('6', 'processamento finalizado')], default='1', max_length=30, verbose_name='Status do Processamento')),
                ('start_processing', models.DateTimeField(blank=True, null=True, verbose_name='Incio do Processamento')),
                ('ending_processing', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Processamento')),
                ('details', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Detalhes do Processamento')),
                ('data', models.JSONField()),
                ('worksheet_id', models.ForeignKey(db_column='worksheet_id', on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_lines', to='worksheets.worksheet')),
            ],
            options={
                'verbose_name': 'Linha',
                'verbose_name_plural': 'Linhas',
            },
        ),
    ]
